# UNTESTED. USERDATABASE IS A WORK IN PROGRESS
# UNTESTED. USERDATABASE IS A WORK IN PROGRESS
# UNTESTED. USERDATABASE IS A WORK IN PROGRESS
# UNTESTED. USERDATABASE IS A WORK IN PROGRESS
# UNTESTED. USERDATABASE IS A WORK IN PROGRESS

postgres:
    image: postgres:latest
    ports:
        - '5432:5432'
    environment: 
        POSTGRES_USER: 'locustuser'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'locustDB'
    VOLUMES:
        